name: "Tests & Coverage badge"

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  generate_coverage_badge:
    if: (github.event_name == 'push' && github.actor != 'coverage_tests_action') || (github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        persist-credentials: false
  
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    
    - name: Install Poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry
  
    - name: Install dependencies
      run: |
        poetry install
    
    - name: Run tests
      run: |
        poetry run pytest

    - name: Install coverage-badge
      run: |
        poetry run pip install coverage-badge
  
    - name: Generate coverage badge
      run: |
        poetry run pytest --cov --cov-report=xml
        poetry run coverage-badge -o coverage.svg -f

    - name: Configure Git
      run: |
        git config --global user.email "coverage_tests_action@github.com"
        git config --global user.name "coverage_tests_action"
    
    - name: Commit and push coverage badge
      run: |
        git config --global user.email "coverage_tests_action@github.com"
        git config --global user.name "coverage_tests_action"
        git add coverage.svg
        git commit -m "Add coverage badge"
        git remote add origin_with_token https://$GH_TOKEN@github.com/$GITHUB_REPOSITORY.git
        git push origin_with_token HEAD:main
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
