name: "Test Suite"

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
  
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    
    - name: Install Poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry
  
    - name: Install dependencies
      run: |
        poetry install
    
    - name: Run tests
      run: |
        poetry run pytest

    - name: Install coverage-badge
      run: |
        poetry run pip install coverage-badge
  
    - name: Generate coverage badge
      run: |
        poetry run pytest --cov --cov-report=xml
        poetry run coverage-badge -o coverage.svg -f

    - name: Commit and push coverage badge
      run: |
        git config --global user.email "coverage_tests_action@github.com"
        git config --global user.name "Coverage badge from GitHub Action"
        git add coverage.svg
        git commit -m "Add coverage badge"
        git push origin main
